use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
xcodeproj 'LYCustomTransitionDemo.xcodeproj'

target 'LYCustomTransitionDemo' do
    pod 'LookinServer', '1.2.6', :configurations => ['Debug']

pod 'SDWebImage', '~> 3.7.0'

end
